//
//  QaArray.swift
//  Brain teasers
//
//  Created by 凱聿蔡凱聿 on 2023/9/22.
//

import UIKit

struct Qa {
    let question: String
    let answer: String
}

struct QaData {
    static let qaArray: [Qa] = [
        Qa(question: "身穿著金色衣服的人(猜四字成語)？", answer: "一鳴驚人(一名金人)"),
        Qa(question: "哞哞叫的牛一下水游泳後就不叫了(猜四字成語)?", answer: "有勇無謀(游泳無哞)"),
        Qa(question: "一隻烏龜，因背著十字架而出了名(猜四字成語)?", answer: "實至名歸(十字名龜)"),
        Qa(question: "兩包麵都被偷了(猜四字成語)?", answer: "面面俱到(俱盜)"),
        Qa(question: "離過50次婚的女人。(猜四字成語)", answer: "前功盡棄(前公盡棄)"),
        Qa(question: "小明為什麼可以連續十幾個小時不眨眼？", answer: "因為在他睡覺"),
        Qa(question: "為什麼小明收到生日禮物，卻把禮物一腳踢開？", answer: "因為禮物是一顆足球"),
        Qa(question: "小明帶100元去買一個75元的東西，但老闆卻只找他5元，為什麼？", answer: "因為小明只給老闆80元"),
        Qa(question: "一個夜黑風高的夜晚，小明伸手不見五指，這是為什麼？", answer: "因為小明只有四根手指頭"),
        Qa(question: "為什麼小明寫了一個字，人人都說他寫了錯字？", answer: "因為他寫的字是「錯」"),
        Qa(question: "一輛客車發生了事故，所有人都受傷了，爲什麼小明卻沒事？", answer: "因爲他不在車上"),
        Qa(question: "小明都有認真刷牙，但別人還說他口臭，爲什麼？", answer: "他老是說髒話"),
        Qa(question: "小明才4歲，卻已當了「爸爸」，可能嗎？", answer: "玩扮家家酒遊戲"),
        Qa(question: "比賽開始了，小明卻使勁往後跑，為什麼？", answer: "拔河"),
        Qa(question: "小明的媽媽把一頭漂亮的長髮剪短了，可是為什麼回到家裡時卻沒有人發現？", answer: "家裡沒人"),
        Qa(question: "小明只會花錢，天天花很多錢，可最後卻成了百萬富翁，為什麼？", answer: "以前是億萬富翁"),
        Qa(question: "下雪天，小明開了暖氣，關上門窗，為什麼還感到很冷？", answer: "他在門外"),
        Qa(question: "紅豆和綠豆混放在一個碟子裡，小明為什麼可以一下子就把它們分開？", answer: "紅豆和綠豆各只有一顆"),
        Qa(question: "家在義大利的小明想去上海，要花多少錢？", answer: "只是想，不用花錢"),
        Qa(question: "想要把夢變為現實，我們做的第一件事情是什麼？", answer: "醒來"),
        Qa(question: "麒麟到了北極會變成什麼？", answer: "冰淇淋(冰麒麟)"),
        Qa(question: "「先天」是父母所遺傳的體質，那「後天」是什麼？", answer: "後天是明天的明天"),
        Qa(question: "哪種水果視力最差？", answer: "芒果"),
        Qa(question: "他走了的英文怎麼說？(猜一國際品牌)", answer: "IKEA(台語諧音)"),
        Qa(question: "離婚的主要起因是什麼？", answer: "結婚"),
        Qa(question: "偷什麼東西不犯法？", answer: "偷笑"),
        Qa(question: "哪一個月有二十八天？", answer: "每個月都有28天"),
        Qa(question: "米的媽媽是誰？", answer: "花(因為花生米)"),
        Qa(question: "製造日期與有效日期同一天的產品是什麼？", answer: "報紙"),
        Qa(question: "有一個人，跟你同父母，卻不是你的兄弟姊妹，他是誰？", answer: "你自己"),
        Qa(question: "一個人在沙灘上走路，為什麼回頭看不見自己的腳印？", answer: "因為他倒著走"),
        Qa(question: "人的右手永遠抓不到什麼？", answer: "右手"),
        Qa(question: "什麼東西往上升了，就永遠都掉不下來？", answer: "年齡"),
        Qa(question: "數字1到9裡面，哪個最懶惰？哪個最勤奮？", answer: "最懶惰是1，最勤奮是2(因為一不做二不休)"),
        Qa(question: "為什麼一隻小北極熊一直懷疑自己不是北極熊？", answer: "因為牠覺得很冷"),
        Qa(question: "為什麼一對健康夫妻生下的三個孩子，都只有一隻左手？", answer: "因為人不可能有兩隻左手"),
        Qa(question: "哪條路越走越暈？", answer: "迷路"),
        Qa(question: "當汽車右轉時，哪顆輪胎不會跟著轉？", answer: "備用輪胎"),
        Qa(question: "一位小胖妞住院，最怕探病的親友跟她說什麼？", answer: "多多保重"),
        Qa(question: "為什麼白鷺鶯總是縮著一隻腳睡覺？", answer: "縮兩隻腳就會跌到"),
        Qa(question: "如果你有一雙翅膀你會做什麼？", answer: "到醫院"),
        Qa(question: "有一座橋上，立一塊牌子，牌子寫著「不准過橋」，但還是有很多人不理會，照樣過橋，為什麼？", answer: "這座橋的名字叫「不准過橋」"),
        Qa(question: "什麼話是全世界通用的？", answer: "電話"),
        Qa(question: "什麼字全世界通用？", answer: "阿拉伯數字"),
        Qa(question: "哭和笑有什麼共同之處？", answer: "都是10筆畫"),
        Qa(question: "爸爸什麼時候像個孩子？", answer: "在爺爺面前"),
        Qa(question: "一位優秀的士兵，在一次站崗值勤時，發現有敵人正在向他悄悄地摸過來，但士兵卻睜一隻眼閉一隻眼，為什麼？", answer: "因為他正在瞄準敵人"),
        Qa(question: "什麼車子寸步難行？", answer: "風車"),
        Qa(question: "哪一顆牙最後一次長出來？", answer: "假牙"),
        Qa(question: "什麼東西最容易滿足？", answer: "襪子"),
        Qa(question: "什麼鴨子用兩隻腳走路？", answer: "所有的鴨子都用兩隻腳走路"),
        Qa(question: "一隻毛毛蟲要過一條沒橋的河，要怎麼過去？", answer: "變成蝴蝶飛過去"),
        Qa(question: "日月潭的中間是什麼?", answer: "是「月」字"),
        Qa(question: "什麼人會一下子變老？?", answer: "新娘(因爲今天是新娘，明天是老婆)"),
        Qa(question: "一顆心值多少錢？", answer: "一億(因爲一心一意)"),
        Qa(question: "颱風天，要帶多少錢才能出門？", answer: "四千萬(因爲颱風天沒「事千萬」不要出門)"),
        Qa(question: "怎樣使麻雀安靜下來？", answer: "壓牠一下(鴉雀無聲；壓雀無聲)"),
        Qa(question: "司機進汽車後第一件事是什麼？", answer: "坐下"),
        Qa(question: "全世界最大的公雞是從哪裏來的？", answer: "雞蛋裡"),
        Qa(question: "全世界最大的蕃薯長在哪裏？", answer: "土裏"),
        Qa(question: "用什麼可以解開所有的謎？", answer: "答案"),
        Qa(question: "青蛙爲什麼能比樹跳得高？", answer: "因爲樹不會跳"),
        Qa(question: "什麼花不能摸？", answer: "火花"),
        Qa(question: "爲什麼大家都喜歡坐著看電影？", answer: "因爲站著看腳會痠"),
        Qa(question: "請龜兔賽跑，請豬來當裁判，請問龜兔誰會贏？", answer: "不能說！說的人是豬…"),
        Qa(question: "小王一邊刷牙，一邊吹著口哨，他是怎麼做到的？", answer: "刷的是假牙"),
        Qa(question: "什麼門永遠關不上?", answer: "球門"),
        Qa(question: "爲什麼有家醫院從不給人看病？", answer: "獸醫院"),
        Qa(question: "什麼瓜不能吃？", answer: "傻瓜"),
        Qa(question: "什麼雨會淋死人?", answer: "槍林彈雨"),
        Qa(question: "上完廁所，要用左手、還是右手擦屁屁會比較好？", answer: "用衛生紙比較好…"),
        Qa(question: "加聯考時，除了准考證之外，最重要的是什麼？", answer: "記得起床、不要遲到"),
        Qa(question: "什麼布切不斷？", answer: "瀑布"),
        Qa(question: "一只螞蟻居然從四川爬到了東京，可能嗎?", answer: "在地圖上爬"),
        Qa(question: "每個人睡覺前，一定不會忘記的事是什麼？", answer: "閉上眼睛"),
        Qa(question: "什麼樣的山和海可以移動？", answer: "人山人海"),
        Qa(question: "能不暈車的最好辦法是什麼？", answer: "走路"),
        Qa(question: "蛋要怎麼買，才不會買到裏面已經孵了小雞的蛋？", answer: "買鴨蛋"),
        Qa(question: "豆腐爲什麼能打傷人？", answer: "因爲是凍豆腐"),
        Qa(question: "如果有人向你問路，你最怕聽到哪一句話？", answer: "這裏是地球嗎？"),
        Qa(question: "有一頭頭朝北的牛，牠向右轉原地轉三圈，然後向後轉原地轉三圈，接著再往右轉，這時候牠尾巴朝哪?", answer: "朝下"),
        Qa(question: "一個男人加一個女人會變成什麼？", answer: "兩個人"),
        Qa(question: "當哥倫布一只腳邁上新大陸後，緊接著做什麼？", answer: "邁另一只腳"),
        Qa(question: "大明的英語非常好，可是有些老外卻聽不懂，爲什麼？", answer: "老外不懂英語"),
        Qa(question: "小學到大學」要念多久？", answer: "不到3秒。不信再念一次：小學到大學"),
        Qa(question: "你爸爸的媽媽的妹妹的女兒的叔叔是你的什麼關係？", answer: "親戚關系"),
        Qa(question: "有個人很餓很餓，而冰箱裏有魚肉罐頭、牛肉罐頭、鳳梨罐頭，他先打開什麼？", answer: "先開冰箱"),
        Qa(question: "這個東西，左看像電燈，右看也像電燈，和電燈沒什麼兩樣。但它就是不會亮，這是什麼呢？", answer: "壞掉的電燈"),
        Qa(question: "有一隻豬，走呀走，走到了美國，這隻豬變成了什麼？", answer: "Pig"),
        Qa(question: "課抽查背課文，小豬、小狗、小貓都舉手，老師會叫誰？", answer: "小狗，因為旺旺仙貝"),
        Qa(question: "動物園裡大象的鼻子最長，那第二長的是誰呢?", answer: "小象"),
        Qa(question: "為什麼拿破崙的字典裡沒有一個「難」字？", answer: "小象因為他的字典是法文"),
        Qa(question: "一位警察的兒子從來不喊這位警察爸爸，為什麼？", answer: "這位員警是個女的"),
        Qa(question: "有一種東西，上升的時候同時會下降，下降的同時會上升，這是什麼？", answer: "蹺蹺板"),
        Qa(question: "蚊子咬在什麼地方你不會覺得癢？", answer: "別人身上"),
        Qa(question: "白色的馬叫白馬，黑色的馬叫黑馬，黑白相間的馬叫斑馬，那麼黑色白色紅色相間的馬叫什麼馬？", answer: "害羞的斑馬"),
        Qa(question: "有一個問題，不論你問任何人，回答都是「沒有」，請問那是什麼問題？", answer: "你睡著了嗎？"),
        Qa(question: "小紅帽從大灰狼面前走過，大灰狼為何沒有認出小紅帽？", answer: "小紅帽今天沒有戴帽子"),
        Qa(question: "什麼東西乾淨時是黑的，髒的時候是白的呢？", answer: "黑板"),
        Qa(question: "你有一艘船，船上有十五位船員，六十位乘客，三百噸貨物。你能根據上面的提示，算出船主的年齡嗎？", answer: "你就是船主年齡還需要算嗎？"),
    ]
}
